Unified routers
OffchainLabs/fund-distribution-contracts pull request #23
Opened 2024-02-23 14:59 UTC by DZGoldman

2024-02-23 15:52 UTC, godzillaba commented on script/FeeRouterDeployer/NovaToDAOTreasury/nova-deploy.s.sol
>          address parentChainTarget = vm.envAddress("L1_TO_DAO_TIMELOCK_ROUTER");
figure out what this is

2024-02-23 21:09 UTC, DZGoldman commented
Testnet deployments: 
sepolia: 0x5DB54b55FfD0887Bf1634a865DB1e7db7a3dd797
arb-sepolia: 0xbDa3ECac5a9a7e61a69252648cC9C66c615ceAA9

2024-02-26 11:55 UTC, gvladika commented on src/FeeRouter/ParentToChildRewardRouter.sol
> +    /// @param parentChainTokenAddr todor
comment needs update

2024-02-26 11:55 UTC, gvladika commented on src/FeeRouter/ParentToChildRewardRouter.sol
> +        emit FundsRouted(amount);
It's the same event that gets emitted when routing Eth. Something like `event FundsRouted(address indexed token, uint256 amount)` would be more useful (also in the case of ChildToParent router)

2024-02-26 12:31 UTC, gzeoneth requested changes

2024-02-26 12:31 UTC, gzeoneth commented on src/FeeRouter/ChildToParentRewardRouter.sol
> +    /// @param _parentChainTokenAddr parent chain (i.e., chaun underlying this one) address of token to route
actually seems like we need to change this function, let's discsuss internally

2024-02-26 12:31 UTC, gzeoneth commented on src/FeeRouter/ChildToParentRewardRouter.sol
> +        _updateDistribution(_parentChainTokenAddr);
agree

2024-03-01 17:21 UTC, merged